### ISSUE TITLE
Feature list to be added to v1

### ISSUE THREAD

**Issue by itjustbong** [itjustbong/lms-tools-extensions#1]
## TODO LIST
- [ ] pip 기능추가
- [ ] 나만의 진도율 기능 추가
- [ ] 강의별 게시판에 댓글 / 평점기능 추가
- [ ] 강의 접속 시간대 데이터화 (모든 사용자 대상)
- [x] 숭파이 자동 연결
